# -*- coding: utf-8 -*-
"""cisproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoVN-BJKBHahmOIGinSZ1G7F9hoF7zK9
"""

import os

print(os.listdir('/content'))

from zipfile import ZipFile

zip_path = "/content/drive/MyDrive/cisproj/archive (1).zip"

extract_path = "/content/AHCD"

with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

import os

for root, dirs, files in os.walk("/content/AHCD"):
    print(root)

# Load Dataset

import os
import cv2
import numpy as np
import pandas as pd

IMG_SIZE = 32

train_folder = "/content/AHCD/Train Images 13440x32x32/train"
test_folder = "/content/AHCD/Test Images 3360x32x32/test"

csv_folder = "/content/AHCD/Arabic Handwritten Characters Dataset CSV"

print("Training Images:", len(os.listdir(train_folder)))
print("Testing Images:", len(os.listdir(test_folder)))

print("\nCSV Files:")

for file in os.listdir(csv_folder):
    print(file)

# Load Images Using Filename Labels

import os
import cv2
import numpy as np

X_train = []
y_train = []

print("Loading Training Images...")

train_images = os.listdir(train_folder)

for img_name in train_images:

    img_path = os.path.join(train_folder, img_name)

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

    img = img.astype("float32") / 255.0

    X_train.append(img.flatten())

    # Extract label from filename
    label = int(img_name.split("_")[-1].replace(".png",""))

    y_train.append(label-1)      # convert 1-28 to 0-27

print("Training Loaded!")

X_test = []
y_test = []

print("Loading Testing Images...")

test_images = os.listdir(test_folder)

for img_name in test_images:

    img_path = os.path.join(test_folder, img_name)

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

    img = img.astype("float32") / 255.0

    X_test.append(img.flatten())

    label = int(img_name.split("_")[-1].replace(".png",""))

    y_test.append(label-1)

print("Testing Loaded!")

X_train=np.array(X_train)
X_test=np.array(X_test)

y_train=np.array(y_train)
y_test=np.array(y_test)

print("Done!")

print(y_train[:20])

# Check Dataset Information


print("Training Shape :", X_train.shape)
print("Testing Shape :", X_test.shape)

print("\nNumber of Classes :", len(np.unique(y_train)))

print("\nFirst 10 Labels:")
print(y_train[:10])

# Display Sample Images


import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(X_train[i].reshape(32,32), cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis("off")

plt.tight_layout()
plt.show()

# Class Distribution


import seaborn as sns

plt.figure(figsize=(12,5))

sns.countplot(x=y_train)

plt.title("Class Distribution")
plt.xlabel("Arabic Character Class")
plt.ylabel("Number of Images")

plt.show()

# Build MLP Model


from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(
    hidden_layer_sizes=(512, 256),
    activation='relu',
    solver='adam',
    max_iter=50,
    random_state=42,
    verbose=True
)

print("MLP Model Created Successfully!")

# Train the Model

print("Training Started...\n")

mlp.fit(X_train, y_train)

print("\nTraining Completed!")

# Predict Test Images


y_pred = mlp.predict(X_test)

print("Prediction Completed!")

# Accuracy


from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

# Precision, Recall and F1 Score


from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print("Precision :", precision)
print("Recall    :", recall)
print("F1 Score  :", f1)

# Classification Report


from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

# Confusion Matrix
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(14,10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")

plt.show()

# Correctly Classified Images


correct = np.where(y_test == y_pred)[0]

plt.figure(figsize=(15,6))

for i in range(10):

    index = correct[i]

    plt.subplot(2,5,i+1)

    plt.imshow(X_test[index].reshape(32,32), cmap="gray")

    plt.title(f"True:{y_test[index]}\nPred:{y_pred[index]}")

    plt.axis("off")

plt.tight_layout()

plt.show()

# Incorrectly Classified Images


incorrect = np.where(y_test != y_pred)[0]

plt.figure(figsize=(15,6))

for i in range(10):

    index = incorrect[i]

    plt.subplot(2,5,i+1)

    plt.imshow(X_test[index].reshape(32,32), cmap="gray")

    plt.title(f"True:{y_test[index]}\nPred:{y_pred[index]}")

    plt.axis("off")

plt.tight_layout()

plt.show()

# Save Model


import joblib

joblib.dump(mlp, "Arabic_MLP_Model.pkl")

print("Model Saved Successfully!")

"""# Conclusion

In this project, a Multi-Layer Perceptron (MLP) classifier was developed for handwritten Arabic character recognition using the Arabic Handwritten Characters Dataset (AHCD).

The character images were preprocessed by converting them into grayscale, normalizing pixel values, and flattening each 32×32 image into a one-dimensional feature vector. The MLP model was trained on the training dataset and evaluated on unseen test images.

The trained model achieved approximately **79% classification accuracy**. Its performance was further evaluated using Precision, Recall, F1-score, Classification Report, and Confusion Matrix. Correctly classified and incorrectly classified handwritten characters were also visualized to analyze the model’s strengths and weaknesses.

The results show that an MLP can effectively classify handwritten Arabic characters, although some errors occur due to similar character shapes and variations in handwriting. More advanced deep learning models, such as Convolutional Neural Networks (CNNs), may further improve classification accuracy.
"""